name = "Server"
author = "Eliot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff5ca13f5dc135db9b5107e58cec47d8804e29c1b58a7899109e6908a9ec5161"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
