name = "Server"
author = "Eliot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba8e69c52c513c5d8093acd12d90ffe8070912cb5ed4cf992d0e76ba6484e98f"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
