name = "Server"
author = "Eliot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8db4674c0d7be4c1bb9942411e9a4a6eea4a963efc081c35287a469688f9012"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
